# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Buildings_damages
                                 A QGIS plugin
  This plugin links a flood damage to every building
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-11-22
        copyright            : (C) 2022 by Giulia Mazzaccaro - Università degli studi di Genova
        email                : giulia.mazzaccaro@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Giulia Mazzaccaro - Università degli studi di Genova'
__date__ = '2022-11-22'
__copyright__ = '(C) 2022 by Giulia Mazzaccaro - Università degli studi di Genova'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Buildings_damages class from file Buildings_damages.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Buildings_damages import Buildings_damagesPlugin
    return Buildings_damagesPlugin()
